[book]
title = "Programming the Cloud"
description = "Learn to program the cloud using examples"
authors = ["Tejaswi Gowda"]
language = "en"


[build]
build-dir = "docs"
create-missing = false

[output.html]
mathjax-support = true
additional-css = ["custom.css", "CNAME"]
additional-js = ["jquery-3.4.1.min.js", "custom.js","iframeResizer.min.js","iframeResizer.contentWindow.min.js"]
default-theme = "coal"

[output.html.playpen]
editable = true
line-numbers = true


[output.html.search]
limit-results = 20
use-boolean-and = true
boost-title = 2
boost-hierarchy = 2
boost-paragraph = 1
expand = true
heading-split-level = 2

#[output.epub]

#[output.latex]
#latex = false 
#pdf = false
